version: '3.8'

services:
  postgres:
    # ... same as above
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  redis:
    # ... same as above
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  backend:
    # ... same as above
    deploy:
      replicas: 3  # Scale to 3 instances
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
